### ISSUE TITLE
The Wire.requestFrom() should not have beginTransmission or endTransmission.

### ISSUE THREAD

**Issue by Koepel** [sparkfun/ISL29125_Breakout#1]
In the file SparkFunISL29125.cpp, the Wire.requestFrom() is encapsulated with Wire.beginTransmission() and Wire.endTransmission(), but the Wire.requestFrom() is a complete I2C transaction on its own.

The Wire.beginTransmission() and Wire.endTransmission() should only be used when writing data to a I2C Slave.

**Comment by loricrotser** [comment]
Verified the flow of the code and commented out the begin and end transmissions around requestFrom function calls
